analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  # Same as strict-casts but for Dart < 2.16
  strong-mode:
    implicit-casts: false

linter:
  rules:
    # Error rules
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    discarded_futures: true
    no_adjacent_strings_in_list: true
    prefer_relative_imports: true

    # Style rules
    always_declare_return_types: true
    avoid_function_literals_in_foreach_calls: false
    avoid_init_to_null: false
    avoid_multiple_declarations_per_line: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cast_nullable_to_non_nullable: true
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: false
    deprecated_consistency: true
    directives_ordering: true
    empty_constructor_bodies: false
    enable_null_safety: true
    flutter_style_todos: true
    implicit_call_tearoffs: true
    missing_whitespace_between_adjacent_strings: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    one_member_abstracts: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: false
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: false
    require_trailing_commas: true
    sized_box_shrink_expand: true
    slash_for_doc_comments: false
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: false
    unnecessary_lambdas: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_to_list_in_spreads: true
    use_colored_box: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: false
    use_named_constants: true
    use_string_buffers: true
    use_super_parameters: true
    void_checks: true